# Generated by Django 3.0.5 on 2020-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='dress', max_length=100),
            preserve_default=False,
        ),
    ]
